export enum SponsorshipStatus {
  FULL = 'FULL',
  NO_SPONSOR = 'NO_SPONSOR',
  SPONSORSHIP_AVAILABLE = 'SPONSORSHIP_AVAILABLE',
  ONE_SPONSORSHIP_POSITION = 'ONE_SPONSORSHIP_POSITION',
  // NO_SPONSORSHIP_POSITION = 'NO_SPONSORSHIP_POSITION',
}

// export enum SPONSOR_PACKAGE_STATUS {
//   NO_SPONSOR = 'NO_SPONSOR',
//   SPONSORED = 'SPONSORED',
// }
