export enum EMITTER {
  UPDATE_ROLE_PERMISSIONS = 'UPDATE_ROLE_PERMISSIONS',
  SYNCHORONIZED_PASSWORD = 'SYNCHORONIZED_PASSWORD',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  SYNCHORONIZED_ACCOUNT = 'SYNCHORONIZED_ACCOUNT',
  SESSION_LOGS = 'SESSION_LOGS',
  SYNCHORONIZED_SCHEDULER_CRON = 'SYNCHORONIZED_SCHEDULER_CRON',
}

export enum SESSION_TYPE {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  UPDATE_USER = 'UPDATE_USER',
}
