export enum PAYLOAD_PROPERTY {
  phone = 'Số điện thoại',
  first_name = 'Tên người dùng',
  last_name = 'Họ người dùng',
  email = 'Email',
  resource = 'Tài nguyên',
  per_page = 'Phân trang',
  page = 'Số trang',
  system = 'Hệ thống',
  password = 'Mật khẩu',
  company = 'Công ty',
  role = 'Chức vụ',
  role_id = 'Chức vụ',
  request_type = 'Loại request',
  verify_type = 'Loại verify',
  contact_phone = 'Số điện thoại liên hệ',
  business_type_id = 'ID Hệ thống',
  business_type_client_id = 'ID client hệ thống',
  business_type_organization_id = 'ID công ty hệ thống',
  is_app = 'Portal/app',
  records = 'Danh sách migrate',
  role_code = 'Mã vai trò',
  gender = 'Giới tính',
  value = 'Giá trị',
  permissions = 'Quyền',
  sponsor_name = 'Tên Chương Trình',
  cover_image = 'Cover image',
  banner_image = 'Banner image',
  product_limited_is_limit = 'Trạng thái hạn chế ngành hàng',
  product_limited_description = 'Mô tả hạn chế ngành hàng',
  start_date = 'Thời gian bắt đầu',
  end_date = 'Thời gian kết thúc',
  sponsorship_expiration_date = 'Thời gian hết hạn tài trợ',
  display_status = 'Trạng thái hiển thị',
  sponsorship_status = 'Trạng thái trài trợ',
  production_status = 'Trạng thái sản xuất',
  short_description = 'Mô tả ngắn',
  detailed_description = 'Mô tả chi tiết',
  introduction_images = 'Hình ảnh giới thiệu',
  sponsor_hashtags = 'Tags',
  casts = 'Người nổi tiếng, KOL tham gia',
  sponsor_categories = 'Thể loại chương trình',
  platforms = 'Danh sách nền tảng',
  sponsorship_forms = 'Hình thức tài trợ',
  sponsorship_packages = 'Giá trị gói tài trợ',
  sponsor_schedulers = 'Lịch trình chương trình',
  sponsor_kpi = 'KPI dự kiến',
  reason_rejected = 'Lý do Admin từ chối duyệt',
  priority = 'Độ ưu tiên hiển thị',
  platform = 'Nền tảng',
  link = 'Nền tảng (link)',
  sponsorship_form = 'Hình thức tài trợ',
  media = 'Hình thức tài trợ (Hình ảnh demo)',
  package_name = 'Tên gói tài trợ',
  package_unit = 'Đơn vị gói tài trợ',
  package_value = 'Giá trị gói tài trợ',
  status = 'Trạng thái tài trơ của gói tài trợ',
}
export enum PAYLOAD_ERROR {
  isString = 'phải là kiểu dữ liệu chuỗi!',
  isNotEmpty = 'là bắt buộc!',
  arrayNotEmpty = 'là bắt buộc!',
  isArray = 'phải là mảng',
  nestedValidation = 'phần tử dữ liệu trong mảng không hợp lệ!',
  minLength = 'tối thiểu',
  maxLength = 'tối đa',
  isEmail = 'không đúng định dạng!',
  isMongoId = 'không đúng định dạng ID!',
  isNumber = 'phải là kiểu dữ liệu số',
  atLeastUpperCase = 'tối thiểu 1 chữ hoa!',
  atLeastLowerCase = 'tối thiểu 1 chữ thường!',
  atLeastSpecialCharater = 'tối thiểu 1 kí tự đặc biệt!',
  atLeastNumber = 'tối thiểu 1 kí tự số',
  verifyConfirmPassword = 'không khớp với mật khẩu!',
  isEnum = 'không thuộc định dạng hợp lệ',
  businessTypeSettingKeyValues = 'không đúng định dạng',
}

export enum ERROR {
  MIN_LENGTH = 'minLength',
  MAX_LENGTH = 'maxLength',
}

export enum COMPARE_ALLOWED_FIELDS {
  UPDATE_STATUS = 'status',
  SYSTEM = 'name,admin_url,base_url,description,name,root_url,redirect_uri',
  COMPANY = 'name,third_party_company_code,contact_phone',
  SCOPE = 'description',
  ROLE = 'name,mapping_code,reference_system',
  USER = 'email,first_name,last_name,avatar',
  MENU = 'name,parent_menu,code',
}

export enum PERMISSION_ACTION {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum DATA_TYPE {
  NUMBER = 'number',
  BOOLEAN = 'boolean',
  OBJECT = 'object',
}

export enum SUB_PAYLOAD_ERROR {
  isValidEmail = 'Mail không hợp lệ',
  isValidPhoneNumber = 'Số điện thoại không hợp lệ',
  notValidatePhoneNumberLength = 'Số điện thoại tối thiểu 10 tối đa 12 số',
  notValidatePhoneNumberOrEmail = 'Mail / Số điện thoại không hợp lệ!',
}
