export enum ENUM_REDIS_FUNCTION_KEY {
  SETTING = 'SETTING',
  USER_PROFILE = 'USER_PROFILE',
  MASTER_DATA = 'MASTER_DATA',
  ROLE = 'ROLE',
}

export enum ENUM_REDIS_TYPE {
  GET = 'GET',
  SET = 'SET',
  DELETE = 'DELETE',
}
